tunnel: d605c844-f284-449c-9454-79224a71e190
credentials-file: "J:/Github/pokemon-showdown/Cloudflare-Server/d605c844-f284-449c-9454-79224a71e190.json"

ingress:
  - hostname: indigostarstorm.com
    path: /~~server/*
    service: http://127.0.0.1:8080

  - hostname: indigostarstorm.com
    service: http://127.0.0.1:8000

  - service: http_status:404