tunnel: 6c44f89b-ae34-4a38-9add-f767a089d0e6
credentials-file: "J:/Github/pokemon-showdown/Cloudflare-Server/6c44f89b-ae34-4a38-9add-f767a089d0e6.json"
ingress:
  - hostname: server.indigostarstorm.com
    service: http://127.0.0.1:8080

  - hostname: indigostarstorm.com
    service: http://127.0.0.1:8000

  - hostname: www.indigostarstorm.com
    service: http://127.0.0.1:8000

  - service: http_status:404